# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Porthole < Formula
  desc "A port kill switch and service viewer for your terminal."
  homepage "https://github.com/subh05sus/porthole"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/subh05sus/porthole/releases/download/v1.1.0/porthole_1.1.0_darwin_amd64.tar.gz"
      sha256 "26d769562762dbe36bd083f1b1d8ea6eeec3236d84e50a654879361e8058ba05"

      define_method(:install) do
        bin.install "porthole"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/subh05sus/porthole/releases/download/v1.1.0/porthole_1.1.0_darwin_arm64.tar.gz"
      sha256 "207f38ac5d7b5bfc7cd3d31eca03c9b227005120697381a2d79876190ed7a840"

      define_method(:install) do
        bin.install "porthole"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/subh05sus/porthole/releases/download/v1.1.0/porthole_1.1.0_linux_amd64.tar.gz"
      sha256 "6d1c83d9e393bcfa0f27eaad3282ca2de10c752cdc314555c34984aafc0abe77"
      define_method(:install) do
        bin.install "porthole"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/subh05sus/porthole/releases/download/v1.1.0/porthole_1.1.0_linux_arm64.tar.gz"
      sha256 "1f8d7e9ca5859d2b2d595692932b51033171415148d1fef8ffbd82705522dd8b"
      define_method(:install) do
        bin.install "porthole"
      end
    end
  end
end
