# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Porthole < Formula
  desc "A port kill switch and service viewer for your terminal."
  homepage "https://github.com/subh05sus/porthole"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/subh05sus/porthole/releases/download/v1.3.0/porthole_1.3.0_darwin_amd64.tar.gz"
      sha256 "669ba3a8e2a97bce8e306fb90b2005b27b221d894dc1945a8741dc000ee10f6c"

      define_method(:install) do
        bin.install "porthole"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/subh05sus/porthole/releases/download/v1.3.0/porthole_1.3.0_darwin_arm64.tar.gz"
      sha256 "858873cfa3b24003e0c3eca1906fea968f0beebd7e9bf206022bde8f2f582ae6"

      define_method(:install) do
        bin.install "porthole"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/subh05sus/porthole/releases/download/v1.3.0/porthole_1.3.0_linux_amd64.tar.gz"
      sha256 "163fb776fa8c4e5bccf28fd5e7689db69fb2d625639cd621837ed69c214d33b1"
      define_method(:install) do
        bin.install "porthole"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/subh05sus/porthole/releases/download/v1.3.0/porthole_1.3.0_linux_arm64.tar.gz"
      sha256 "b348c0d8fd068ba563c662ef8a2ab029267c2757819da2f376e802a2d539e2ab"
      define_method(:install) do
        bin.install "porthole"
      end
    end
  end
end
